DROP TABLE LISTINGS;
DROP SEQUENCE listing_pkey_seq;

CREATE SEQUENCE listing_pkey_seq INCREMENT 1 START 1000;

CREATE TABLE LISTINGS (LISTING_ID BIGINT NOT NULL,
                      PICTURE_URL VARCHAR(200),
                      LISTED_PRICE NUMERIC NOT NULL,
                      BEDROOMS FLOAT4 NOT NULL ,
                      BATHROOMS FLOAT4 NOT NULL ,
                      PROPERTY_TYPE VARCHAR(30) NOT NULL ,
                      PROPERTY_TAX NUMERIC,
                      DESCRIPTION TEXT,
                      LISTING_STATUS VARCHAR(30) NOT NULL ,
                      PROVINCE VARCHAR(2),
                      CITY VARCHAR(50),
                      POSTAL_CODE VARCHAR(6),
                      DATE_CREATED TIMESTAMP,
                      DATE_UPDATED TIMESTAMP,
  CONSTRAINT listings_pkey PRIMARY KEY (LISTING_ID)
) WITH(OIDS=FALSE);

CREATE INDEX IDX_LISTINGS_CITY ON LISTINGS(CITY);
CREATE INDEX IDX_LISTINGS_PROVINCE ON LISTINGS(PROVINCE);
CREATE INDEX IDX_LISTINGS_PRICE ON LISTINGS(LISTED_PRICE);
CREATE INDEX IDX_LISTINGS_BEDROOMS ON LISTINGS(BEDROOMS);